# Generated by Django 2.1.1 on 2018-12-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='occupation',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='userregister',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
