# Generated by Django 2.1.1 on 2018-12-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRE', '0002_auto_20181214_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='userregister',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
