# Generated by Django 2.1.1 on 2018-12-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRE', '0005_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Customer_Email',
            field=models.EmailField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
